FROM php:5.6-apache
COPY ./content/ /var/www/html/
# COPY ./apache-conf/sites-available/000-default.conf /etc/apache2/sites-available/
# COPY ./apache-conf/ports.conf /etc/apache2/
# EXPOSE 8080
# RUN apt-get update -y && apt-get install -y net-tools vim telnet nano
# RUN service apache2 reload
